src/j64.Harmony.Web/Controllers/CustomCommandController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using j64.Harmony.Web.ViewModels.Configure;
using j64.Harmony.Web.Models;
using j64.Harmony.Xmpp;
using j64.Harmony.Web.Repository;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace j64.Harmony.Web.Controllers
{
    public class CustomCommandController : Controller
    {
        private j64HarmonyGateway j64Config = null;
        private Hub myHub = null;

        #region Constructor
        public CustomCommandController(j64HarmonyGateway j64Config, Hub hub)
        {
            this.j64Config = j64Config;
            myHub = hub;
        }
        #endregion

        #region Index
        public IActionResult Index()
        {
            // If not connected to the smart hub go to the configure page
            if (myHub.hubConfig == null || String.IsNullOrEmpty(j64Config.ChannelDevice) || String.IsNullOrEmpty(j64Config.VolumeDevice))
                return RedirectToAction("Edit", "FirstTimeConfig");

            if (String.IsNullOrEmpty(OauthRepository.Get().accessToken))
                return RedirectToAction("Index", "Oauth");

            return View(CreateCustomCommandView());
        }

        private List<CustomCommandViewModel> CreateCustomCommandView()
        {
            List<CustomCommandViewModel> l = new List<CustomCommandViewModel>();
            foreach (var customCommand in this.j64Config.CustomCommands)
            {
                var ccvm = new CustomCommandViewModel()
                {
                    CommandName = customCommand.CommandName
                };

                int i = 1;
                foreach (var ca in customCommand.Actions)
                {
                    var cc = new ViewModels.Configure.CustomCommand()
                    {
                        Sequence = i,
                        Device = ca.Device,
                        ControlGroup = ca.Group,
                        Function = ca.Function
                    };
                    ccvm.commands.Add(cc);
                    i++;
                }

                l.Add(ccvm);
            }

            return l;
        }
        #endregion

        #region Add new command
        public IActionResult CreateCommand(string command)
        {
            int i = 0;
            foreach (var cmd in j64Config.CustomCommands)
            {
                if (cmd.CommandName.StartsWith("New Command"))
                    i++;
            }
            string cmdName = "New Command";
            if (i > 0)
                cmdName += " " + i.ToString();

            var cc = new CustomCommandViewModel()
            {
                OriginalCommandName = cmdName,
                CommandName = cmdName
            };

            return View("EditCommand", cc);
        }
        #endregion

        #region Edit Command
        public IActionResult EditCommand(string command)
        {
            var customCommand = j64Config.CustomCommands.Find(x => x.CommandName == command);
            if (customCommand == null)
                return View("Index", CreateCustomCommandView());

            var cc = new CustomCommandViewModel()
            {
                OriginalCommandName = customCommand.CommandName,
                CommandName = customCommand.CommandName
            };
            return View(cc);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditCommand(CustomCommandViewModel command)
        {
            var customCommand = j64Config.CustomCommands.Find(x => x.CommandName == command.OriginalCommandName);
            if (customCommand == null)
            {
                customCommand = new Models.CustomCommand()
                {
                    CommandName = command.CommandName
                };
                j64Config.CustomCommands.Add(customCommand);
            }
            customCommand.CommandName = command.CommandName;

            for (int i = 0; i < customCommand.Actions.Count; i++)
                customCommand.Actions[i].Sequence = i + 1;
            j64HarmonyGatewayRepository.Save(j64Config);

            return View("Index", CreateCustomCommandView());
        }
        #endregion

        #region Delete Command
        public IActionResult DeleteCommand(string command)
        {
            var customCommand = j64Config.CustomCommands.Find(x => x.CommandName == command);
            if (customCommand != null)
                j64Config.CustomCommands.Remove(customCommand);

            return View("Index", CreateCustomCommandView());
        }
        #endregion

        #region Add Action
        public IActionResult AddNewAction(string command, int sequence)
        {
            var customCommand = j64Config.CustomCommands.Find(x => x.CommandName == command);

            var cav = new CustomActionViewModel()
            {
                Command = command,
                Sequence = sequence,
            };

            cav.Devices = myHub.hubConfig.device;

            return View(cav);
        }

        public IActionResult SelectNewAction(string command, int sequence, string device, string group, string function)
        {
            var selectedDevice = myHub.hubConfig.device.Find(x => x.label == device);
            var selectedGroup = selectedDevice?.controlGroup.Find(x => x.name == group);
            var selectedFunction = selectedGroup?.function.Find(x => x.label == function);

            var customCommand = j64Config.CustomCommands.Find(x => x.CommandName == command);
            var customActionIndex = customCommand?.Actions.FindIndex(x => x.Sequence == sequence);

            customCommand.Actions.Insert(sequence, new CustomAction()
            {
                Device = device,
                Group = group,
                Function = function,
                Command = "press",
            });

            for (int i = 0; i < customCommand.Actions.Count; i++)
                customCommand.Actions[i].Sequence = i + 1;
            j64HarmonyGatewayRepository.Save(j64Config);

            return View("Index", CreateCustomCommandView());
        }
        #endregion

        #region Delete Action
        public IActionResult DeleteAction(string command, int sequence)
        {
            var customCommand = j64Config.CustomCommands.Find(x => x.CommandName == command);
            var customActionIndex = customCommand.Actions.FindIndex(x => x.Sequence == sequence);
            if (customActionIndex >= 0)
            {
                customCommand.Actions.RemoveAt(customActionIndex);
                for (int i = 0; i < customCommand.Actions.Count; i++)
                    customCommand.Actions[i].Sequence = i + 1;
                j64HarmonyGatewayRepository.Save(j64Config);
            }
            return View("Index", CreateCustomCommandView());
        }
        #endregion

        #region Move Action
        public IActionResult MoveActionUp(string command, int sequence)
        {
            var customCommand = j64Config.CustomCommands.Find(x => x.CommandName == command);
            var customActionIndex = customCommand.Actions.FindIndex(x => x.Sequence == sequence);
            if (customActionIndex > 0)
            {
                var customAction = customCommand.Actions[customActionIndex];
                customCommand.Actions.RemoveAt(customActionIndex);
                customCommand.Actions.Insert(customActionIndex - 1, customAction);
                for (int i = 0; i < customCommand.Actions.Count; i++)
                    customCommand.Actions[i].Sequence = i + 1;
                j64HarmonyGatewayRepository.Save(j64Config);
            }
            return View("Index", CreateCustomCommandView());
        }
        #endregion

        public IActionResult SyncSmartThings()
        {
            SmartThingsRepository.InstallDevices(j64Config, Request.Host.Value);
            return View("Index", CreateCustomCommandView());
        }
    }
}

src/j64.Harmony.Web/Controllers/DeviceNamesController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using j64.Harmony.Web.ViewModels.Configure;
using j64.Harmony.Xmpp;
using Microsoft.AspNetCore.Mvc.Rendering;
using j64.Harmony.Web.Models;
using j64.Harmony.Web.Repository;

namespace j64.Harmony.Web.Controllers
{
    public class DeviceNamesController : Controller
    {
        private Hub myHub;
        private j64HarmonyGateway myj64Config;

        public DeviceNamesController(j64HarmonyGateway j64Config, Hub hub)
        {
            myj64Config = j64Config;
            myHub = hub;
        }

        #region Edit
        public IActionResult Edit()
        {
            // If not connected to the smart hub go to the configure page
            if (myHub.hubConfig == null || String.IsNullOrEmpty(myj64Config.ChannelDevice) || String.IsNullOrEmpty(myj64Config.VolumeDevice))
                return RedirectToAction("Edit", "FirstTimeConfig");

            if (String.IsNullOrEmpty(OauthRepository.Get().accessToken))
                return RedirectToAction("Index", "Oauth");

            return View(CreateViewMode());
        }

        private List<SelectListItem> GetDeviceList(string selectectValue)
        {
            List<SelectListItem> l = new List<SelectListItem>();
            l.Add(new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem() { Text = "" });

            myHub.hubConfig?.device.ForEach(x => 
                {
                    var sli = new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem()
                    {
                        Text = x.label,
                        Selected = (x.label == selectectValue)
                    };

                    l.Add(sli);
                });

            return l;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(DeviceNamesViewModel deviceNames)
        {
            if (ModelState.IsValid)
            {
                myj64Config.SoundDeviceName = deviceNames.SoundDeviceName;
                myj64Config.ChannelSurfDeviceName = deviceNames.ChannelSurfDeviceName;
                myj64Config.LastChannelDeviceName = deviceNames.LastChannelDeviceName;
                myj64Config.VcrPauseDeviceName = deviceNames.VcrPauseDeviceName;

                myj64Config.VolumeDevice = deviceNames.VolumeDevice;
                myj64Config.ChannelDevice = deviceNames.ChannelDevice;
                myj64Config.ChanneKeyPauseInterval = deviceNames.ChanneKeyPauseInterval;

                j64HarmonyGatewayRepository.Save(myj64Config);
            }

            deviceNames.VolumeDeviceList = GetDeviceList(deviceNames.VolumeDevice);
            deviceNames.ChannelDeviceList = GetDeviceList(deviceNames.ChannelDevice);
            return View(deviceNames);
        }

        #endregion


        public IActionResult SyncSmartThings()
        {
            SmartThingsRepository.InstallDevices(myj64Config, Request.Host.Value);
            return View("Edit", CreateViewMode());
        }
        
        private DeviceNamesViewModel CreateViewMode()
        {
            var dvm = new DeviceNamesViewModel()
            {
                ChanneKeyPauseInterval = myj64Config.ChanneKeyPauseInterval,
                ChannelDevice = myj64Config.ChannelDevice,
                ChannelSurfDeviceName = myj64Config.ChannelSurfDeviceName,
                LastChannelDeviceName = myj64Config.LastChannelDeviceName,
                SoundDeviceName = myj64Config.SoundDeviceName,
                VcrPauseDeviceName = myj64Config.VcrPauseDeviceName,
                VolumeDevice = myj64Config.VolumeDevice,
            };

            dvm.VolumeDeviceList = GetDeviceList(dvm.VolumeDevice);
            dvm.ChannelDeviceList = GetDeviceList(dvm.ChannelDevice);
            
            return dvm;
        }
    }
}

src/j64.Harmony.Web/Controllers/FavoriteChannelController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using j64.Harmony.Web.ViewModels.Configure;
using j64.Harmony.Web.Models;
using j64.Harmony.Xmpp;
using j64.Harmony.Web.Repository;

namespace j64.Harmony.Web.Controllers
{
    public class FavoriteChannelController : Controller
    {
        private j64HarmonyGateway j64Config = null;
        private Hub myHub = null;

        public FavoriteChannelController(j64HarmonyGateway j64Config, Hub hub)
        {
            this.j64Config = j64Config;
            myHub = hub;
        }

        public IActionResult Index()
        {
            // If not connected to the smart hub go to the configure page
            if (myHub.hubConfig == null || String.IsNullOrEmpty(j64Config.ChannelDevice) || String.IsNullOrEmpty(j64Config.VolumeDevice))
                return RedirectToAction("Edit", "FirstTimeConfig");

            if (String.IsNullOrEmpty(OauthRepository.Get().accessToken))
                return RedirectToAction("Index", "Oauth");

            List<FavoriteChannelViewModel> l = new List<FavoriteChannelViewModel>();
            j64Config.FavoriteChannels.ForEach(x => l.Add(new FavoriteChannelViewModel() { ChannelNumber = x.Channel, Name = x.Name }));

            return View(l);
        }

        #region Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(FavoriteChannelViewModel favoriteChannel)
        {
            // Test for a pre-existing channel!
            var fcx = j64Config.FavoriteChannels.Find(x => x.Channel == favoriteChannel.ChannelNumber);
            if (fcx != null)
                ModelState.AddModelError("ChannelNumber", "This channel number already exists");

            fcx = j64Config.FavoriteChannels.Find(x => x.Name == favoriteChannel.Name);
            if (fcx != null)
                ModelState.AddModelError("Name", "This channel name already exists");

            if (ModelState.IsValid == false)
                return View(favoriteChannel);

            // Add this channel to the config
            j64Config.FavoriteChannels.Add(new FavoriteChannel()
            {
                Channel = favoriteChannel.ChannelNumber,
                Name = favoriteChannel.Name
            });
            j64HarmonyGatewayRepository.Save(j64Config);

            // Return to the list
            return RedirectToAction("Index");
        }
        #endregion

        #region Edit
        public IActionResult Edit(string channel)
        {
            if (channel == null)
                return NotFound();

            var hubFc = j64Config.FavoriteChannels.Find(x => x.Channel == channel);
            if (hubFc == null)
                return NotFound();

            // Return the view model entry
            FavoriteChannelViewModel fc = new FavoriteChannelViewModel()
            {
                ChannelNumber = hubFc.Channel,
                Name = hubFc.Name
            };

            return View(fc);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(FavoriteChannelViewModel favoriteChannel)
        {
            var hubFc = j64Config.FavoriteChannels.Find(x => x.Channel == favoriteChannel.ChannelNumber);
            if (hubFc == null)
                ModelState.AddModelError("ChannelNumber", "This channel no longer exists");

            var hubFcn = j64Config.FavoriteChannels.Find(x => x.Name == favoriteChannel.Name);
            if (hubFcn != null)
                ModelState.AddModelError("Name", "This channel name already exists");


            if (ModelState.IsValid == false)
                return View(favoriteChannel);

            hubFc.Name = favoriteChannel.Name;
            j64HarmonyGatewayRepository.Save(j64Config);

            return RedirectToAction("Index");
        }
        #endregion

        #region Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(string channel)
        {
            var fcx = j64Config.FavoriteChannels.Find(x => x.Channel == channel);
            if (fcx != null)
                j64Config.FavoriteChannels.Remove(fcx);

            return RedirectToAction("Index");
        }
        #endregion

        public IActionResult SyncSmartThings()
        {
            SmartThingsRepository.InstallDevices(j64Config, Request.Host.Value);
            return View("Index", j64Config);
        }
    }
}

src/j64.Harmony.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - j64.Harmony.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand" style="font-size: 14px;"><i class="fa fa-microphone"></i> j64 Harmony</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Configure <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="FavoriteChannel" asp-action="Index"><i class="fa fa-file-audio-o fa-fw"></i> Favorite Channels</a></li>
                            <li><a asp-controller="CustomCommand" asp-action="Index"><i class="fa fa-file-audio-o fa-fw"></i> Custom Commands</a></li>
                            <li><a asp-controller="HubsAndGateways" asp-action="Edit"><i class="fa fa-server fa-fw"></i> Hubs &amp; Gateways</a></li>
                            <li><a asp-controller="DeviceNames" asp-action="Edit"><i class="fa fa-file-audio-o fa-fw"></i> Device Names</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a asp-controller="Oauth" asp-action="Index"><i class="fa fa-cloud-upload fa-fw"></i> Install Smart App</a></li>
                        </ul>
                    </li>
                    <li>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - j64</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>