src/j64.Harmony.Web/Models/ConfigureViewModels/OauthViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace j64.Harmony.Web.ViewModels.Configure
{
    public class OauthViewModel
    {
        public string STUserId { get; set; }
        public string STPassword { get; set; }
        public string ClientKey { get; set; }
        public string SecretKey { get; set; }
    }
}

src/j64.Harmony.Web/Controllers/OAuthController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using j64.Harmony.Web.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Hosting;
using j64.Harmony.Web.Repository;
using j64.Harmony.Web.ViewModels.Configure;
using j64.Harmony.Xmpp;
using System.Threading.Tasks;

namespace j64.Harmony.Web.Controllers
{
    public class OAuthController : Controller
    {
        j64HarmonyGateway j64Config;
        IHostingEnvironment myEnv;
        Hub myHub;

        public OAuthController(j64HarmonyGateway j64Config, Hub hub, IHostingEnvironment env)
        {
            this.j64Config = j64Config;
            this.myEnv = env;
            this.myHub = hub;
        }

        public IActionResult Index()
        {
            if (myHub.hubConfig == null || String.IsNullOrEmpty(j64Config.ChannelDevice) || String.IsNullOrEmpty(j64Config.VolumeDevice))
                return RedirectToAction("Edit", "FirstTimeConfig");

            var oauth = OauthRepository.Get();
            var ovm = new OauthViewModel()
            {
                ClientKey = oauth.clientKey,
                SecretKey = oauth.secretKey
            };

            return View(ovm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateSmartApp(OauthViewModel authInfo)
        {
            if (ModelState.IsValid == false)
                return View(authInfo);

            var conn = new SmartThingsConnection();
            if (await conn.Login(authInfo.STUserId, authInfo.STPassword) == false)
            {
                ModelState.AddModelError("STPassword", "Could not connect to smart things using the supplied credentials");
                return View("Index", authInfo);
            }

            var cs = new DeviceTypeRepository(conn, "j64 Channel Switch", $"{myEnv.WebRootPath}/../SmartThingApps/j64ChannelSwitchDevice.groovy");
            var ss = new DeviceTypeRepository(conn, "j64 Surfing Switch", $"{myEnv.WebRootPath}/../SmartThingApps/j64SurfingSwitchDevice.groovy");
            var vs = new DeviceTypeRepository(conn, "j64 VCR Switch", $"{myEnv.WebRootPath}/../SmartThingApps/j64VcrSwitchDevice.groovy");
            var os = new DeviceTypeRepository(conn, "j64 Volume Switch", $"{myEnv.WebRootPath}/../SmartThingApps/j64VolumeSwitchDevice.groovy");
            var cc = new DeviceTypeRepository(conn, "j64 Custom Command Switch", $"{myEnv.WebRootPath}/../SmartThingApps/j64CustomCommandSwitchDevice.groovy");

            var har = new SmartAppRepository(conn, "j64 Harmony", $"{myEnv.WebRootPath}/../SmartThingApps/j64HarmonySmartApp.groovy");

            // Save the client/secret keys
            var oauth = OauthRepository.Get();
            oauth.clientKey = har.clientKey;
            oauth.secretKey = har.secretKey;
            OauthRepository.Save(oauth);

            var ovm = new OauthViewModel()
            {
                ClientKey = oauth.clientKey,
                SecretKey = oauth.secretKey
            };

            return View("Index", ovm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BeginAuth([Bind("clientKey", "secretKey")] OauthInfo authInfo)
        {
            string authorizedUrl = "http://" + this.Request.Host.Value + this.Url.Content("~/OAuth/Authorized");

            // Reset the token info
            authInfo.accessToken = null;
            authInfo.tokenType = null;
            authInfo.expiresInSeconds = 0;

            OauthRepository.Save(authInfo);

            string Url = $"https://graph.api.smartthings.com/oauth/authorize?response_type=code&scope=app&redirect_uri={authorizedUrl}&client_id={authInfo.clientKey}";

            return Redirect(Url);
        }

        public IActionResult Authorized(string code)
        {
            OauthInfo oai = OauthRepository.Get();

            if (code == null)
                return View(oai);

            oai.authCode = code;

            System.Net.Http.HttpClient client = new System.Net.Http.HttpClient();

            var url = "https://graph.api.smartthings.com/oauth/token";

            List<KeyValuePair<string, string>> parms = new List<KeyValuePair<string, string>>();
            parms.Add(new KeyValuePair<string, string>("grant_type", "authorization_code"));
            parms.Add(new KeyValuePair<string, string>("code", oai.authCode));
            parms.Add(new KeyValuePair<string, string>("client_id", oai.clientKey));
            parms.Add(new KeyValuePair<string, string>("client_secret", oai.secretKey));
            string authorizedUrl = "http://" + this.Request.Host.Value + this.Url.Content("~/OAuth/Authorized");
            parms.Add(new KeyValuePair<string, string>("redirect_uri", authorizedUrl));

            var content = new System.Net.Http.FormUrlEncodedContent(parms);
            var response = client.PostAsync(url, content);
            response.Wait();

            if (response.Result.StatusCode != System.Net.HttpStatusCode.OK)
            {
                ViewData.Add("GetTokenError", "Get Auth Code Error: " + response.Result.StatusCode.ToString());
                return View(oai);
            }

            // Save the interim result
            var val = JsonConvert.DeserializeObject<Dictionary<string, string>>(response.Result.Content.ReadAsStringAsync().Result);
            oai.accessToken = val["access_token"];
            oai.expiresInSeconds = Convert.ToInt32(val["expires_in"]);
            oai.tokenType = val["token_type"];
            OauthRepository.Save(oai);

            // Get the endpoint info
            client = new System.Net.Http.HttpClient();
            url = "https://graph.api.smartthings.com/api/smartapps/endpoints";

            System.Net.Http.HttpRequestMessage msg = new System.Net.Http.HttpRequestMessage(System.Net.Http.HttpMethod.Get, url);
            msg.Headers.Add("Authorization", $"Bearer {oai.accessToken}");

            response = client.SendAsync(msg);
            response.Wait();

            if (response.Result.StatusCode != System.Net.HttpStatusCode.OK)
            {
                ViewData.Add("GetTokenError", "Get EndPoints Error: " + response.Result.StatusCode.ToString());
                return View(oai);
            }

            string jsonString = response.Result.Content.ReadAsStringAsync().Result;
            oai.endpoints = JsonConvert.DeserializeObject<List<OauthEndpoint>>(jsonString);

            OauthRepository.Save(oai);

            // Prepare the smart app to be called from the local traffic
            SmartThingsRepository.PrepTheInstall(j64Config);

            // Send all of the default devices to the smart app
            SmartThingsRepository.InstallDevices(j64Config, Request.Host.Value);

            // all done!
            return View(oai);

        }
    }
}

src/j64.Harmony.Web/Views/OAuth/Authorized.cshtml
@model j64.Harmony.Web.Models.OauthInfo
@{
    ViewData["Title"] = "Authorized Page";
}

<div class="panel panel-default">
    <div class="panel-heading">  
        OAuth Results
    </div>
    <div class="panel-body">
        @if (ViewData["GetTokenError"] != null)
        {
                <i class='fa fa-exclamation-triangle' style='color:red'></i>
            <p>
                Something went wrong during the authorization process and an access token was not received.  <br/>
                The HTTP Error was: @ViewData["GetTokenError"]
            </p>
        }
        else
        {
            <i class="fa fa-check-circle" style='color:green'></i>
            <p>Your app was successfully authorized and an access token has been saved to your SmartThing.json config file.  
            Your harmony system will now start synchronizing with the smart thing devices.</p>
            <p>If you do not see any of the volume or channel devices appear in smart things, there may have been an 
               issue determining the smart things hub ip address.  You can set it manually on the home page.</p>
        }
    </div>
</div>

src/j64.Harmony.Web/Views/OAuth/Index.cshtml
@model j64.Harmony.Web.ViewModels.Configure.OauthViewModel
@{
    ViewData["Title"] = "Authorize Your Smart App";
}
<br/>
<form asp-controller="OAuth" asp-action="CreateSmartApp" method="post">
    <div class="panel panel-default">
        <div class="panel-heading">
            If you want this app to automatically add the smart app and device type, supply your SmartThings id/password
        </div>
        <div class="panel-body">
            <div class="form-group">
                <label asp-for="STUserId">Smartthings ID</label>
                <input asp-for="STUserId" class="form-control" placeholder="Smart Things User ID" />
                <span asp-validation-for="STUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="STPassword">SmartThings Password</label>
                <input asp-for="STPassword" class="form-control" placeholder="Smart Things Password" type="password" />
                <span asp-validation-for="STPassword" class="text-danger"></span>
            </div>
            <button class="btn btn-primary btn-xs" type="submit">Create Devices</button>
        </div>
    </div>
</form>
<form asp-controller="OAuth" asp-action="BeginAuth" method="post">
    <div class="panel panel-default">
        <div class="panel-heading">
            Enter your client key and secret key from the smarthings IDE
        </div>
        <div class="panel-body">
            <div class="form-group">
                <label asp-for="ClientKey">SmartApp Client Key</label>
                <input asp-for="ClientKey" class="form-control" placeholder="smartapp client key" />
                <span asp-validation-for="ClientKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecretKey">SmartApp Secret Key</label>
                <input asp-for="SecretKey" class="form-control" placeholder="smartapp secret key" />
                <span asp-validation-for="SecretKey" class="text-danger"></span>
            </div>
            <button class="btn btn-primary btn-xs" type="submit">Begin Authorization</button>
        </div>
    </div>
    @if (String.IsNullOrEmpty(Model.ClientKey) == false)
    {
        <p style='font-size: small; font-style: italic; margin-left: 20px; margin-right: 20px;'>
            Note: You have already obtained an authorization key so it is not necessary to
            re-authorize this app with smart things.  If your client or secret
            key has changed or you are experiencing issues synchronizing with smart things,
            you can run back through this authorization process to obtain a new
            authorization token.  It does not cause an issue to re-authorize the app
            even if the existing authorization key is valid.
        </p>
    }
</form>